# Generated by Django 5.0.6 on 2024-06-09 11:43

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_location_user_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
    ]
