# Generated by Django 5.0.6 on 2024-06-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_district_alter_user_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.FloatField(db_default=0),
        ),
    ]
