# Generated by Django 5.0.6 on 2024-06-22 09:03

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_transaction_status_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='chek',
            field=models.ImageField(blank=True, null=True, upload_to='users/transaction'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(default='process', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='text',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text'),
        ),
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
