# Generated by Django 5.0.6 on 2024-06-09 10:52

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='category/')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('status', models.CharField(
                    choices=[('new', 'New'), ('visit', 'Vist'), ('ready', 'Ready'), ('delivery', 'Delivery'),
                             ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('archived', 'Archived'),
                             ('missed_call', 'MISSED CALL')], default='new', max_length=30)),
                ('quantity', models.IntegerField(default=1)),
                ('courier', models.ForeignKey(blank=True, null=True, limit_choices_to={'type': 'courier'},
                                              on_delete=django.db.models.deletion.SET_NULL,
                                              related_name='courier', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(blank=True, null=True, limit_choices_to={'type': 'operator'},
                                               on_delete=django.db.models.deletion.SET_NULL,
                                               related_name='operator', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                           related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                             to='apps.stream')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.product')),
                ('region', models.CharField(blank=True, max_length=30, null=True)),
                ('views_count', models.IntegerField(db_default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True))
            ],
            options={
                'ordering': ['-created_at']
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(editable=False, max_length=255)),
                ('price', models.IntegerField(db_default=0)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('shopping_cost', models.IntegerField()),
                ('extra_balance', models.IntegerField(db_default=0)),
                ('image', models.ImageField(upload_to='product/')),
                ('count', models.IntegerField(db_default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at']
            },
        ),
    ]
