# Generated by Django 5.0.6 on 2024-06-09 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='like',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        )
    ]
