# Generated by Django 5.0.6 on 2024-07-02 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='likemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'courier'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='operator',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'operator'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='referral_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ArchivedOrderProxyModel',
            fields=[
            ],
            options={
                'verbose_name': 'Archived Order',
                'verbose_name_plural': 'Archived Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.order',),
        ),
        migrations.CreateModel(
            name='CancelledOrderProxyModel',
            fields=[
            ],
            options={
                'verbose_name': 'Cancelled Order',
                'verbose_name_plural': 'Cancelled Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.order',),
        ),
        migrations.CreateModel(
            name='DeliveredOrderProxyModel',
            fields=[
            ],
            options={
                'verbose_name': 'Delivered Order',
                'verbose_name_plural': 'Delivered Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.order',),
        ),
        migrations.CreateModel(
            name='DeliveryOrderProxyModel',
            fields=[
            ],
            options={
                'verbose_name': 'Delivery Order',
                'verbose_name_plural': 'Delivery Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.order',),
        ),
        migrations.CreateModel(
            name='MissedCallOrderProxyModel',
            fields=[
            ],
            options={
                'verbose_name': 'Missed Call Order',
                'verbose_name_plural': 'Missed Call Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.order',),
        ),
        migrations.CreateModel(
            name='NewOrderProxyModel',
            fields=[
            ],
            options={
                'verbose_name': 'New Order',
                'verbose_name_plural': 'New Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.order',),
        ),
        migrations.CreateModel(
            name='OrderHistoryProxyModel',
            fields=[
            ],
            options={
                'verbose_name': 'History Order',
                'verbose_name_plural': 'History Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.order',),
        ),
        migrations.CreateModel(
            name='ReadyOrderProxyModel',
            fields=[
            ],
            options={
                'verbose_name': ' Ready Order',
                'verbose_name_plural': 'Ready Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.order',),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='apps.category'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='apps.product'),
        ),
        migrations.AddField(
            model_name='likemodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.product'),
        ),
        migrations.AddField(
            model_name='stream',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stream',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='apps.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='apps.stream'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClientTransactionProxyModel',
            fields=[
            ],
            options={
                'verbose_name': 'Client Transaction',
                'verbose_name_plural': 'Client Transactions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.transaction',),
        ),
        migrations.CreateModel(
            name='OperatorTransactionProxyModel',
            fields=[
            ],
            options={
                'verbose_name': 'Operator Transaction',
                'verbose_name_plural': 'Operator Transactions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.transaction',),
        ),
        migrations.CreateModel(
            name='TransactionCancelledProxyModel',
            fields=[
            ],
            options={
                'verbose_name': 'Cancelled Transaction',
                'verbose_name_plural': 'Cancelled Transactions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.transaction',),
        ),
        migrations.CreateModel(
            name='TransactionPaidProxyModel',
            fields=[
            ],
            options={
                'verbose_name': 'Paid Transaction',
                'verbose_name_plural': 'Paid Transactions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.transaction',),
        ),
        migrations.CreateModel(
            name='TransactionProcessProxyModel',
            fields=[
            ],
            options={
                'verbose_name': 'Process Transaction',
                'verbose_name_plural': 'Processes Transactions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.transaction',),
        ),
    ]
