# Generated by Django 5.0.6 on 2024-06-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0012_product_extra_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='discount',
            field=models.FloatField(default=0),
        ),
    ]
