# Generated by Django 5.0.6 on 2024-06-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0013_alter_stream_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='extra_balance',
            field=models.IntegerField(db_default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='shopping_cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='stream',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
