# Generated by Django 5.0.6 on 2024-06-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0015_alter_product_options_product_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(db_default=0),
        ),
    ]
