# Generated by Django 5.0.6 on 2024-06-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0016_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='views_count',
            field=models.IntegerField(db_default=0),
        ),
    ]
