# Generated by Django 5.0.6 on 2024-06-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0017_order_views_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedOrderProxyModel',
            fields=[
            ],
            options={
                'verbose_name': 'Archived Order',
                'verbose_name_plural': 'Archived Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.order',),
        ),
        migrations.CreateModel(
            name='CancelledOrderProxyModel',
            fields=[
            ],
            options={
                'verbose_name': 'Cancelled Order',
                'verbose_name_plural': 'Cancelled Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.order',),
        ),
        migrations.CreateModel(
            name='DeliveredOrderProxyModel',
            fields=[
            ],
            options={
                'verbose_name': 'Delivered Order',
                'verbose_name_plural': 'Delivered Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.order',),
        ),
        migrations.CreateModel(
            name='DeliveryOrderProxyModel',
            fields=[
            ],
            options={
                'verbose_name': 'Delivery Order',
                'verbose_name_plural': 'Delivery Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.order',),
        ),
        migrations.CreateModel(
            name='MissedCallOrderProxyModel',
            fields=[
            ],
            options={
                'verbose_name': 'MissedCall Order',
                'verbose_name_plural': 'MissedCall Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.order',),
        ),
        migrations.CreateModel(
            name='NewOrderProxyModel',
            fields=[
            ],
            options={
                'verbose_name': 'New Order',
                'verbose_name_plural': 'New Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.order',),
        ),
        migrations.CreateModel(
            name='ReadyOrderProxyModel',
            fields=[
            ],
            options={
                'verbose_name': 'Ready Order',
                'verbose_name_plural': 'Ready Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.order',),
        ),
        migrations.CreateModel(
            name='VisitOrderProxyModel',
            fields=[
            ],
            options={
                'verbose_name': 'Visit Order',
                'verbose_name_plural': 'Visit Orders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.order',),
        ),
        migrations.RemoveField(
            model_name='order',
            name='views_count',
        ),
        migrations.AddField(
            model_name='stream',
            name='views_count',
            field=models.IntegerField(db_default=0),
        ),
    ]
