# Generated by Django 5.0.6 on 2024-06-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0018_archivedorderproxymodel_cancelledorderproxymodel_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisitOrderProxyModel',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('ready', 'Ready'), ('delivery', 'Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('archived', 'Archived'), ('missed_call', 'MISSED CALL')], default='new', max_length=30),
        ),
    ]
