# Generated by Django 5.0.6 on 2024-06-19 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0029_alter_stream_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stream',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='apps.stream'),
        ),
    ]
