# Generated by Django 5.0.6 on 2024-06-19 14:39

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0031_alter_order_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_sum', models.IntegerField()),
                ('text', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('min_sum', models.IntegerField()),
            ],
        ),
    ]
