# Generated by Django 5.0.6 on 2024-06-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0034_rename_active_competition_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
