# Generated by Django 5.0.6 on 2024-06-21 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0036_rename_settings_setting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'Site Setting'},
        ),
        migrations.AlterField(
            model_name='setting',
            name='operator_sum',
            field=models.IntegerField(verbose_name='operator uchun beriladigan pul'),
        ),
    ]
