# Generated by Django 5.0.6 on 2024-06-22 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0037_alter_setting_options_alter_setting_operator_sum'),
    ]

    operations = [
    ]
