# Generated by Django 5.0.6 on 2024-06-22 18:33

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0039_remove_product_shopping_cost_setting_shopping_cost_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivedorderproxymodel',
            options={'verbose_name': 'Order Archived'},
        ),
        migrations.AlterModelOptions(
            name='cancelledorderproxymodel',
            options={'verbose_name': 'Order Cancelled'},
        ),
        migrations.AlterModelOptions(
            name='deliveredorderproxymodel',
            options={'verbose_name': 'Order Delivered'},
        ),
        migrations.AlterModelOptions(
            name='deliveryorderproxymodel',
            options={'verbose_name': 'Order Delivery', 'verbose_name_plural': 'Order Delivery'},
        ),
        migrations.AlterModelOptions(
            name='likemodel',
            options={'verbose_name': 'Like'},
        ),
        migrations.AlterModelOptions(
            name='missedcallorderproxymodel',
            options={'verbose_name': 'Order MissedCall', 'verbose_name_plural': 'Order MissedCalls'},
        ),
        migrations.AlterModelOptions(
            name='neworderproxymodel',
            options={'verbose_name': 'Order New', 'verbose_name_plural': 'Order News'},
        ),
        migrations.AlterModelOptions(
            name='readyorderproxymodel',
            options={'verbose_name': 'Order Ready', 'verbose_name_plural': 'Order Ready'},
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='process', max_length=10)),
                ('card_number', models.CharField(max_length=16)),
                ('summa', models.FloatField(db_default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('text', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Text')),
                ('chek', models.ImageField(blank=True, null=True, upload_to='apps/transaction')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionCancelledProxyModel',
            fields=[
            ],
            options={
                'verbose_name': 'Transaction Cancelled',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.transaction',),
        ),
        migrations.CreateModel(
            name='TransactionPaidProxyModel',
            fields=[
            ],
            options={
                'verbose_name': 'Transaction Paid',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.transaction',),
        ),
        migrations.CreateModel(
            name='TransactionProcessProxyModel',
            fields=[
            ],
            options={
                'verbose_name': 'Transaction Process',
                'verbose_name_plural': 'Transaction Processes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.transaction',),
        ),
    ]
