# Generated by Django 5.0.6 on 2024-06-23 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0041_rename_setting_sitesetting_orderhistoryproxymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='summa',
            new_name='amount',
        ),
    ]
