# Generated by Django 5.0.6 on 2024-06-24 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0042_rename_summa_transaction_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorTransactionProxyModel',
            fields=[
            ],
            options={
                'verbose_name': 'Transaction Operator',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.transaction',),
        ),
        migrations.CreateModel(
            name='UserTransactionProxyModel',
            fields=[
            ],
            options={
                'verbose_name': 'Transaction Client',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('apps.transaction',),
        ),
    ]
