# Generated by Django 5.0.6 on 2024-06-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('apps', '0044_delete_usertransactionproxymodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('process', 'Process'), ('canceled', 'Canceled'), ('paid', 'Paid')],
                                   default='process', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(db_default=0),
        )
    ]
