# Generated by Django 5.0.6 on 2024-06-27 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0045_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivedorderproxymodel',
            options={'verbose_name': 'Order Archived', 'verbose_name_plural': 'Orders Archived'},
        ),
        migrations.AlterModelOptions(
            name='cancelledorderproxymodel',
            options={'verbose_name': 'Order Cancelled', 'verbose_name_plural': 'Orders Cancelled'},
        ),
        migrations.AlterModelOptions(
            name='clienttransactionproxymodel',
            options={'verbose_name': 'Transaction Client', 'verbose_name_plural': 'Transaction Clients'},
        ),
        migrations.AlterModelOptions(
            name='deliveredorderproxymodel',
            options={'verbose_name': 'Order Delivered', 'verbose_name_plural': 'Orders Delivered'},
        ),
        migrations.AlterModelOptions(
            name='deliveryorderproxymodel',
            options={'verbose_name': 'Order Delivery', 'verbose_name_plural': 'Order Deliverys'},
        ),
        migrations.AlterModelOptions(
            name='operatortransactionproxymodel',
            options={'verbose_name': 'Transaction Operator', 'verbose_name_plural': 'Transaction Operators'},
        ),
        migrations.AlterModelOptions(
            name='readyorderproxymodel',
            options={'verbose_name': 'Order Ready', 'verbose_name_plural': 'Orders Readys'},
        ),
        migrations.AlterModelOptions(
            name='transactioncancelledproxymodel',
            options={'verbose_name': 'Transaction Cancelled', 'verbose_name_plural': 'Transactions Cancelled'},
        ),
        migrations.AlterModelOptions(
            name='transactionpaidproxymodel',
            options={'verbose_name': 'Transaction Paid', 'verbose_name_plural': 'Transactions Paid'},
        ),
    ]
