# Generated by Django 5.0.6 on 2024-06-27 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0046_alter_archivedorderproxymodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archivedorderproxymodel',
            options={'verbose_name': 'Archived Order', 'verbose_name_plural': 'Archived Orders'},
        ),
        migrations.AlterModelOptions(
            name='cancelledorderproxymodel',
            options={'verbose_name': 'Cancelled Order', 'verbose_name_plural': 'Cancelled Orders'},
        ),
        migrations.AlterModelOptions(
            name='clienttransactionproxymodel',
            options={'verbose_name': 'Client Transaction', 'verbose_name_plural': 'Client Transactions'},
        ),
        migrations.AlterModelOptions(
            name='deliveredorderproxymodel',
            options={'verbose_name': 'Delivered Order', 'verbose_name_plural': 'Delivered Orders'},
        ),
        migrations.AlterModelOptions(
            name='deliveryorderproxymodel',
            options={'verbose_name': 'Delivery Order', 'verbose_name_plural': 'Delivery Orders'},
        ),
        migrations.AlterModelOptions(
            name='missedcallorderproxymodel',
            options={'verbose_name': 'MissedCall Order', 'verbose_name_plural': 'MissedCall Orders'},
        ),
        migrations.AlterModelOptions(
            name='neworderproxymodel',
            options={'verbose_name': 'New Order', 'verbose_name_plural': 'New Orders'},
        ),
        migrations.AlterModelOptions(
            name='operatortransactionproxymodel',
            options={'verbose_name': 'Operator Transaction', 'verbose_name_plural': 'Operator Transactions'},
        ),
        migrations.AlterModelOptions(
            name='readyorderproxymodel',
            options={'verbose_name': ' Ready Order', 'verbose_name_plural': 'Ready Orders'},
        ),
        migrations.AlterModelOptions(
            name='transactioncancelledproxymodel',
            options={'verbose_name': 'Cancelled Transaction', 'verbose_name_plural': 'Cancelled Transactions'},
        ),
        migrations.AlterModelOptions(
            name='transactionpaidproxymodel',
            options={'verbose_name': 'Paid Transaction', 'verbose_name_plural': 'Paid Transactions'},
        ),
        migrations.AlterModelOptions(
            name='transactionprocessproxymodel',
            options={'verbose_name': 'Process Transaction', 'verbose_name_plural': 'Processes Transactions'},
        ),
    ]
