# Generated by Django 5.0.6 on 2024-06-27 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0047_alter_archivedorderproxymodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderhistoryproxymodel',
            options={'verbose_name': 'History Order', 'verbose_name_plural': 'History Orders'},
        ),
    ]
