# Generated by Django 5.0.6 on 2024-06-27 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0048_alter_orderhistoryproxymodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='missedcallorderproxymodel',
            options={'verbose_name': 'Missed Call Order', 'verbose_name_plural': 'Missed Call Orders'},
        ),
    ]
